import type { Metadata } from "next";
import { LegalShell } from "@/components/legal-shell";

export const metadata: Metadata = {
  title: "Terms of Service — FinCopilot",
  description: "The terms governing your use of FinCopilot.",
};

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" updated="July 13, 2026">
      <p>
        These Terms govern your access to and use of FinCopilot (the &quot;Service&quot;). By using
        the Service you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        FinCopilot is an AI research assistant that retrieves and synthesizes information from public
        company filings and market data and returns cited answers. Outputs are generated by AI and
        may be incomplete or incorrect.
      </p>

      <h2>2. Not investment advice</h2>
      <p>
        <strong>
          FinCopilot is an informational research tool only. It is not investment, financial, legal,
          or tax advice, and it does not execute trades.
        </strong>{" "}
        You are solely responsible for your decisions. Always verify figures against primary sources
        before acting.
      </p>

      <h2>3. Acceptable use</h2>
      <ul>
        <li>Do not use the Service unlawfully or to infringe others&apos; rights.</li>
        <li>Do not attempt to breach security, scrape at abusive rates, or reverse-engineer models.</li>
        <li>Do not upload content you lack the right to process.</li>
      </ul>

      <h2>4. AI-generated content</h2>
      <p>
        In line with transparency requirements (including EU AI Act Article 50), we disclose that you
        are interacting with an AI system and that answers are AI-generated. Content may contain
        errors; a faithfulness gate refuses unsupported claims but does not guarantee accuracy.
      </p>

      <h2>5. Accounts &amp; plans</h2>
      <p>
        Paid plans, quotas, and billing terms are described at checkout. Usage may be metered. We may
        change features or limits with reasonable notice.
      </p>

      <h2>6. Disclaimers &amp; liability</h2>
      <p>
        The Service is provided &quot;as is&quot; without warranties. To the maximum extent permitted
        by law, we are not liable for any indirect or consequential damages, or for decisions made in
        reliance on Service outputs.
      </p>

      <h2>7. Changes &amp; contact</h2>
      <p>
        We may update these Terms; material changes will be posted here. Questions:{" "}
        <a href="mailto:legal@fincopilot.app">legal@fincopilot.app</a>.
      </p>
    </LegalShell>
  );
}
